inc:
  title:        "EatMeSF"
  subtitle:     "Food pimps"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  company:      EatMeSF
  url:          http://www.eatmesf.com/
  facebook:     eatmesf
  twitter:      eatmesf
  gplus:        '101183822199340201470'
  about_link:   /about
  product_link: /the_guide
  tagline: "Get a modern guide for your city"
  disqus:
    shortname: false
  sharing:
    twitter: true
    facebook: true
    gplus: true
    hn: false
  analytics:
    google:
      id: 'UA-41789029-1'
  google_font: 'PT+Sans'
url: http://www.eatmesf.com
exclude:
  - README.md
  - LICENSE
  - Rakefile
  - Gemfile
  - Gemfile.lock
permalink: pretty
paginate: 10
assets:
  js_compressor: uglifier
  css_compressor: sass
